name: 'Generate and Upload Reports to S3'
description: 'Upload Playwright reports and update reports index on S3'

inputs:
  artifact-name:
    description: 'Name for the artifact upload'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
  browser-name:
    description: 'Browser name for the report'
    required: true
  is-manual-execution:
    description: 'Whether this is a manual execution (true/false)'
    required: true
    type: 'boolean'
    default: 'false'
  testdino_api_key:
    description: 'Testdino API Key from the GitHub secrets'
    required: true

outputs:
  smart-report-url:
    description: 'URL of the uploaded smart report'
    value: ${{ steps.upload-smart-report.outputs.smart-report-url }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Playwright-smart-reporter historical
      uses: actions/cache@v4
      with:
        path: test-history.json
        key: test-history-${{ github.ref }}-${{ github.run_number }}
        restore-keys: |
          test-history-${{ github.ref }}-
          test-history-

    - name: Download test history from S3
      shell: bash
      run: |
        mkdir -p history

        # Clean branch name for folder structure
        CLEAN_BRANCH=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/_/g')
        mkdir -p "history/${CLEAN_BRANCH}"

        # Download main history file
        aws s3 cp s3://kaleidos-qa-reports/test-history.json main-history.json 2>/dev/null || echo "No main history file found"

        # Download branch-specific history files
        aws s3 sync s3://kaleidos-qa-reports/history/${CLEAN_BRANCH}/ history/${CLEAN_BRANCH}/ 2>/dev/null || echo "No branch-specific history found"

    - name: Merge downloaded histories with current
      shell: bash
      run: |
        CLEAN_BRANCH=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/_/g')

        # Ensure playwright-smart-reporter is available for merge CLI
        if ! npm list playwright-smart-reporter > /dev/null 2>&1; then
          echo "Installing playwright-smart-reporter for merge CLI..."
          npm install playwright-smart-reporter
        fi

        # Create array of history files to merge
        HISTORY_FILES=()

        # Add current test history if it exists
        if [ -f "test-history.json" ]; then
          HISTORY_FILES+=("test-history.json")
          echo "Found current history file: test-history.json"
        fi

        # Add downloaded main history file if it exists
        if [ -f "main-history.json" ]; then
          HISTORY_FILES+=("main-history.json")
          echo "Found main history file: main-history.json"
        fi

        # Add branch-specific history files
        if [ -d "history/${CLEAN_BRANCH}" ]; then
          for file in history/${CLEAN_BRANCH}/history_*.json; do
            if [ -f "$file" ]; then
              HISTORY_FILES+=("$file")
              echo "Found branch history file: $file"
            fi
          done
        fi

        # If we have multiple history files, merge them
        if [ ${#HISTORY_FILES[@]} -gt 1 ]; then
          echo "Merging ${#HISTORY_FILES[@]} history files..."
          npx playwright-smart-reporter-merge-history "${HISTORY_FILES[@]}" -o merged-history.json --max-runs 15
          
          if [ -f "merged-history.json" ]; then
            mv merged-history.json test-history.json
            echo "✅ Successfully merged history files"
            echo "📊 Final history runs count: $(node -pe 'try { JSON.parse(require("fs").readFileSync("test-history.json", "utf8")).runs?.length || 0 } catch(e) { 0 }')"
          else
            echo "❌ Failed to merge history files"
          fi
        elif [ ${#HISTORY_FILES[@]} -eq 1 ]; then
          echo "Using single history file: ${HISTORY_FILES[0]}"
          if [ "${HISTORY_FILES[0]}" != "test-history.json" ]; then
            cp "${HISTORY_FILES[0]}" test-history.json
          fi
        else
          echo "No history files found"
        fi

        # Configure baseline for comparison
        if [ -f "test-history.json" ]; then
          LATEST_RUN_ID=$(node -e "
            try {
              const fs = require('fs');
              const data = fs.readFileSync('test-history.json', 'utf8');
              const history = JSON.parse(data);
              if (history.runs && Array.isArray(history.runs) && history.runs.length > 0) {
                const currentRunId = '${{ github.run_id }}';
                const sortedRuns = history.runs
                  .filter(run => run && run.runId && String(run.runId) !== String(currentRunId))
                  .sort((a, b) => {
                    const dateA = new Date(a.timestamp || 0);
                    const dateB = new Date(b.timestamp || 0);
                    return dateB.getTime() - dateA.getTime();
                  });
                if (sortedRuns.length > 0 && sortedRuns[0].runId) {
                  console.log(String(sortedRuns[0].runId));
                }
              }
            } catch (e) { }
          " 2>/dev/null)
          
          if [ -n "$LATEST_RUN_ID" ] && [ "$LATEST_RUN_ID" != "undefined" ] && [ "$LATEST_RUN_ID" != "null" ]; then
            echo "BASELINE_RUN_ID=$LATEST_RUN_ID" >> $GITHUB_ENV
            echo "✅ Set baseline run ID: $LATEST_RUN_ID"
          fi
        fi

    - name: Upload report and update index on S3
      shell: bash
      run: |
        # Upload report to S3
        mkdir -p reports/run-${{ github.run_id }}

        # Check if playwright-report directory exists
        if [ -d "playwright-report" ] && [ "$(ls -A playwright-report 2>/dev/null)" ]; then
          cp -r playwright-report/* reports/run-${{ github.run_id }}/
          echo "✅ Playwright report copied to upload directory"
        else
          # Create placeholder files if no report exists
          echo "<h1>No Test Report</h1><p>Tests may not have been executed or failed to generate report.</p>" > reports/run-${{ github.run_id }}/index.html
          echo '{"status": "no-tests-run", "timestamp": "'$(date -Iseconds)'"}' > reports/run-${{ github.run_id }}/results.json
          echo "⚠️ No playwright report found, created placeholder"
        fi

        aws s3 sync reports/run-${{ github.run_id }}/ s3://kaleidos-qa-reports/run-${{ github.run_id }}/
        echo "✅ Report uploaded: https://kaleidos-qa-reports.s3.eu-west-1.amazonaws.com/run-${{ github.run_id }}/index.html"

        # Download current index from S3 (if exists)
        aws s3 cp s3://kaleidos-qa-reports/index.html current_index.html 2>/dev/null || echo "No existing index found, creating new one"

        # Calculate metadata
        MONTH=$(date -u +%m)
        if [[ "$MONTH" =~ ^(04|05|06|07|08|09|10)$ ]]; then
          DATE_TIME=$(date -u -d "+2 hours" +"%Y-%m-%d %H:%M CEST")
        else
          DATE_TIME=$(date -u -d "+1 hour" +"%Y-%m-%d %H:%M CET")
        fi
        SHORT_SHA="${{ github.sha }}"
        SHORT_SHA=${SHORT_SHA:0:7}
        BRANCH_NAME="${{ github.ref_name }}"
        WORKFLOW_NAME="${{ github.workflow }}"

        # Success percentage and browser setup
        SUCCESS_PERCENT="N/A"; SUCCESS_CLASS="success-medium"
        if [ -f "testResults.json" ]; then
          SUCCESS_PERCENT=$(node -e "try { console.log(Math.round(JSON.parse(require('fs').readFileSync('testResults.json', 'utf8')).PercentPassed || 0) + '%'); } catch(e) { console.log('N/A'); }")
          if [[ "$SUCCESS_PERCENT" != "N/A" ]]; then
            PERCENT_NUM=$(echo "$SUCCESS_PERCENT" | sed 's/%//')
            if [[ $PERCENT_NUM -ge 90 ]]; then
              SUCCESS_CLASS="success-high"
            elif [[ $PERCENT_NUM -ge 30 ]]; then
              SUCCESS_CLASS="success-medium"
            else
              SUCCESS_CLASS="success-low"
            fi
          fi
        fi

        if [[ "${{ inputs.browser-name }}" = "Firefox" ]]; then
          BROWSER_ICON="🦊"
          BROWSER_LABEL="Firefox"
        elif [[ "${{ inputs.browser-name }}" = "Webkit" ]]; then
          BROWSER_ICON="🦎"
          BROWSER_LABEL="WebKit"
        else
          BROWSER_ICON="🌐"
          BROWSER_LABEL="Chrome"
        fi
        if [[ "$WORKFLOW_NAME" == "Manual Penpot Tests for PR" ]]; then
          WORKFLOW_LABEL="PR_manual"
        elif [[ "$WORKFLOW_NAME" =~ firefox ]] || [[ "$WORKFLOW_NAME" =~ Firefox ]]; then
          WORKFLOW_LABEL="PRE_firefox"
        elif [[ "$WORKFLOW_NAME" =~ webkit ]] || [[ "$WORKFLOW_NAME" =~ Webkit ]]; then
          WORKFLOW_LABEL="PRE_webkit"
        else
          WORKFLOW_LABEL="PRE_chrome_daily"
        fi

        # Generate updated index.html
        {
          sed -n '1,/<!-- ROWS_PLACEHOLDER -->/p' .github/html-template.html | head -n -1
          echo "          <tr>"
          echo "            <td class=\"success-rate $SUCCESS_CLASS\" data-label=\"📊 Success %\">$SUCCESS_PERCENT</td>"
          echo "            <td class=\"workflow\" data-label=\"🔄 Workflow\">$WORKFLOW_LABEL</td>"
          echo "            <td class=\"commit\" data-label=\"📝 Commit\"><a href=\"https://github.com/${{ github.repository }}/commit/${{ github.sha }}\">$SHORT_SHA</a></td>"
          echo "            <td class=\"date\" data-label=\"📅 Date\">$DATE_TIME</td>"
          echo "            <td class=\"branch\" data-label=\"🌿 Branch\">$BRANCH_NAME</td>"
          echo "            <td class=\"browser\" data-label=\"🌐 Browser\"><span title=\"$BROWSER_LABEL\">$BROWSER_ICON $BROWSER_LABEL</span></td>"
          echo "            <td data-label=\"📊 Report\"><a href=\"https://kaleidos-qa-reports.s3.eu-west-1.amazonaws.com/run-${{ github.run_id }}/index.html\">🔍 View Report</a></td>"
          echo "          </tr>"
          [ -f current_index.html ] && sed -n '/<tbody>/,/<\/tbody>/p' current_index.html | sed '1d;$d;/<!-- ROWS_PLACEHOLDER -->/d;/^[[:space:]]*$/d' || true
          sed -n '/<!-- ROWS_PLACEHOLDER -->/,$p' .github/html-template.html | tail -n +2
        } > new_index.html

        # Upload updated index to S3 with proper content type and caching
        aws s3 cp new_index.html s3://kaleidos-qa-reports/index.html \
          --content-type "text/html" \
          --cache-control "max-age=300" \
          --metadata-directive REPLACE

        echo "✅ Index updated on S3: https://kaleidos-qa-reports.s3.eu-west-1.amazonaws.com/index.html"

        # Cleanup
        rm -f current_index.html new_index.html

    - name: Upload smart report to S3
      id: upload-smart-report
      shell: bash
      run: |
        # Check for smart report in multiple possible locations
        SMART_REPORT_PATH=""
        if [ -f "smart-report.html" ]; then
          SMART_REPORT_PATH="smart-report.html"
        elif [ -f "playwright-report/smart-report.html" ]; then
          SMART_REPORT_PATH="playwright-report/smart-report.html"
        elif [ -f "tests/smart-report.html" ]; then
          SMART_REPORT_PATH="tests/smart-report.html"
        else
          echo "<h1>Smart Report Placeholder</h1><p>Generated at $(date)</p>" > smart-report.html
          SMART_REPORT_PATH="smart-report.html"
        fi

        if [ -n "$SMART_REPORT_PATH" ]; then
          aws s3 cp "$SMART_REPORT_PATH" s3://kaleidos-qa-reports/run-${{ github.run_id }}/smart-report.html \
            --content-type "text/html" \
            --cache-control "max-age=300" \
            --metadata-directive REPLACE
          
          SMART_REPORT_URL="https://kaleidos-qa-reports.s3.eu-west-1.amazonaws.com/run-${{ github.run_id }}/smart-report.html"
          echo "smart-report-url=$SMART_REPORT_URL" >> $GITHUB_OUTPUT
        else
          echo "smart-report-url=" >> $GITHUB_OUTPUT
        fi

    - name: Check and save history file for cache
      shell: bash
      run: |
        CLEAN_BRANCH=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/_/g')

        # Check multiple possible locations for history file
        HISTORY_FILE_PATH=""
        if [ -f "test-history.json" ]; then
          HISTORY_FILE_PATH="test-history.json"
        elif [ -f "tests/test-history.json" ]; then
          HISTORY_FILE_PATH="tests/test-history.json"
        elif [ -f "playwright-report/test-history.json" ]; then
          HISTORY_FILE_PATH="playwright-report/test-history.json"
        fi

        if [ -n "$HISTORY_FILE_PATH" ]; then
          # Copy history file to root for consistency (only if not already there)
          if [ "$HISTORY_FILE_PATH" != "test-history.json" ]; then
            cp "$HISTORY_FILE_PATH" test-history.json
          fi
          
          # Save branch-specific history file with run ID
          HISTORY_FILE="test-history_${{ github.run_id }}_$(date +%Y%m%d_%H%M%S).json"
          mkdir -p "history/${CLEAN_BRANCH}"
          cp test-history.json "history/${CLEAN_BRANCH}/${HISTORY_FILE}"
          
          # Upload main history to S3
          aws s3 cp test-history.json s3://kaleidos-qa-reports/test-history.json \
            --content-type "application/json" \
            --cache-control "max-age=300" \
            --metadata-directive REPLACE
          
          # Upload branch-specific history structure to S3
          aws s3 sync "history/${CLEAN_BRANCH}/" s3://kaleidos-qa-reports/history/${CLEAN_BRANCH}/ \
            --content-type "application/json" \
            --cache-control "max-age=300"
          
          # Clean old history files (keep only last 10 per branch)
          (cd "history/${CLEAN_BRANCH}" && ls -t history_*.json | tail -n +11 | xargs rm -f 2>/dev/null) || true
        fi

    - name: Testdino Reporter
      shell: bash
      run: |
        npx --yes tdpw playwright-report/ --token="${{ inputs.testdino_api_key }}" --upload-html  --upload-traces --json-report playwright-report/results.json
        echo "✅ Report uploaded to TestDino ('is-manual-execution': ${{ inputs.is-manual-execution }})"
      if: ${{ inputs.is-manual-execution == 'false'}}

    - name: Upload artifact backup
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: playwright-report/
        retention-days: 7
        if-no-files-found: ignore
      if: ${{ !inputs.is-manual-execution }}
