name: 'Generate and Upload Reports'
description: 'Download existing reports, prepare history and upload to GitHub Pages'

inputs:
  browser-name:
    description: 'Browser name for the report'
    required: true
  artifact-name:
    description: 'Name for the artifact upload'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS and upload report to S3
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Upload report to S3
      shell: bash
      run: |
        # Create and upload report to S3
        mkdir -p reports/run-${{ github.run_id }}
        cp -r playwright-report/* reports/run-${{ github.run_id }}/
        aws s3 cp reports/run-${{ github.run_id }}/ s3://kaleidos-qa-reports/run-${{ github.run_id }}/ --recursive
        echo "✅ Report uploaded: https://kaleidos-qa-reports.s3.eu-west-1.amazonaws.com/run-${{ github.run_id }}/index.html"

    - name: Update reports index and push to gh-pages
      shell: bash
      run: |
        # Checkout gh-pages optimized
        git clone --depth 1 --branch gh-pages https://github.com/${{ github.repository }}.git gh-pages-temp
        cd gh-pages-temp
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git config gc.auto 0 && git config pack.window 1

        # Calculate metadata in one block
        MONTH=$(date -u +%m)
        [[ "$MONTH" =~ ^(04|05|06|07|08|09|10)$ ]] && DATE_TIME=$(date -u -d "+2 hours" +"%Y-%m-%d %H:%M CEST") || DATE_TIME=$(date -u -d "+1 hour" +"%Y-%m-%d %H:%M CET")
        SHORT_SHA="${{ github.sha }}"
        SHORT_SHA=${SHORT_SHA:0:7}
        BRANCH_NAME="${{ github.ref_name }}"
        WORKFLOW_NAME="${{ github.workflow }}"

        # Success percentage and browser setup
        SUCCESS_PERCENT="N/A"; SUCCESS_CLASS="success-medium"
        if [ -f "../testResults.json" ]; then
          SUCCESS_PERCENT=$(node -e "try { console.log(Math.round(JSON.parse(require('fs').readFileSync('../testResults.json', 'utf8')).PercentPassed || 0) + '%'); } catch(e) { console.log('N/A'); }")
          [[ "$SUCCESS_PERCENT" != "N/A" ]] && PERCENT_NUM=${SUCCESS_PERCENT%\%} && [[ $PERCENT_NUM -ge 90 ]] && SUCCESS_CLASS="success-high" || [[ $PERCENT_NUM -ge 30 ]] && SUCCESS_CLASS="success-medium" || SUCCESS_CLASS="success-low"
        fi

        [[ "${{ inputs.browser-name }}" = "Firefox" ]] && BROWSER_ICON="🦊" && BROWSER_LABEL="Firefox" || { BROWSER_ICON="🌐"; BROWSER_LABEL="Chrome"; }
        [[ "$WORKFLOW_NAME" == "Manual Penpot Tests for PR" ]] && WORKFLOW_LABEL="PR_Manual" || [[ "$WORKFLOW_NAME" =~ firefox|Firefox ]] && WORKFLOW_LABEL="PRE_daily_firefox" || WORKFLOW_LABEL="PRE_daily"

        # Generate complete updated index in one operation
        {
          sed -n '1,/<!-- ROWS_PLACEHOLDER -->/p' ../github/html-template.html | head -n -1
          echo "          <tr>"
          echo "            <td class=\"success-rate $SUCCESS_CLASS\" data-label=\"📊 Success %\">$SUCCESS_PERCENT</td>"
          echo "            <td class=\"workflow\" data-label=\"🔄 Workflow\">$WORKFLOW_LABEL</td>"
          echo "            <td class=\"commit\" data-label=\"📝 Commit\"><a href=\"https://github.com/${{ github.repository }}/commit/${{ github.sha }}\">$SHORT_SHA</a></td>"
          echo "            <td class=\"date\" data-label=\"📅 Date\">$DATE_TIME</td>"
          echo "            <td class=\"branch\" data-label=\"🌿 Branch\">$BRANCH_NAME</td>"
          echo "            <td class=\"browser\" data-label=\"🌐 Browser\"><span title=\"$BROWSER_LABEL\">$BROWSER_ICON $BROWSER_LABEL</span></td>"
          echo "            <td data-label=\"📊 Report\"><a href=\"https://kaleidos-qa-reports.s3.eu-west-1.amazonaws.com/run-${{ github.run_id }}/index.html\">🔍 View Report</a></td>"
          echo "          </tr>"
          [ -f index.html ] && sed -n '/<tbody>/,/<\/tbody>/p' index.html | sed '1d;$d;/<!-- ROWS_PLACEHOLDER -->/d;/^[[:space:]]*$/d' || true
          sed -n '/<!-- ROWS_PLACEHOLDER -->/,$p' ../github/html-template.html | tail -n +2
        } > index.html

        # Commit and push optimized
        git add index.html
        if ! git diff --staged --quiet; then
          LAST_MSG=$(git log -1 --pretty=%B 2>/dev/null || echo "")
          if [[ "$LAST_MSG" =~ ^"Update reports index -" ]]; then
            git commit --amend -m "Update reports index - $(date -u +%Y%m%d)" --no-verify
            git push --force-with-lease origin gh-pages
          else
            git commit -m "Update reports index - $(date -u +%Y%m%d)" --no-verify
            git push origin gh-pages
          fi
          echo "✅ Index updated and pushed to gh-pages"
          git gc --prune=now --aggressive >/dev/null 2>&1 || true
        fi

        cd .. && rm -rf gh-pages-temp
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload artifact backup
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: playwright-report/
        retention-days: 7
        if-no-files-found: ignore
