name: 'Generate and Upload Reports to S3'
description: 'Upload Playwright reports and update reports index on S3'

inputs:
  artifact-name:
    description: 'Name for the artifact upload'
    required: true
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true
  browser-name:
    description: 'Browser name for the report'
    required: true
  is-manual-execution:
    description: 'Whether this is a manual execution (true/false)'
    required: true
    type: 'boolean'
    default: 'false'
  testdino_api_key:
    description: 'Testdino API Key from the GitHub secrets'
    required: true

outputs:
  smart-report-url:
    description: 'URL of the uploaded smart report'
    value: ${{ steps.upload-smart-report.outputs.smart-report-url }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Playwright-smart-reporter historical
      uses: actions/cache@v4
      with:
        path: test-history.json
        key: test-history-${{ github.ref }}
        restore-keys: test-history-

    - name: Upload report and update index on S3
      shell: bash
      run: |
        # Upload report to S3
        mkdir -p reports/run-${{ github.run_id }}
        cp -r playwright-report/* reports/run-${{ github.run_id }}/
        aws s3 sync reports/run-${{ github.run_id }}/ s3://kaleidos-qa-reports/run-${{ github.run_id }}/
        echo "✅ Report uploaded: https://kaleidos-qa-reports.s3.eu-west-1.amazonaws.com/run-${{ github.run_id }}/index.html"

        # Download current index from S3 (if exists)
        aws s3 cp s3://kaleidos-qa-reports/index.html current_index.html 2>/dev/null || echo "No existing index found, creating new one"

        # Calculate metadata
        MONTH=$(date -u +%m)
        if [[ "$MONTH" =~ ^(04|05|06|07|08|09|10)$ ]]; then
          DATE_TIME=$(date -u -d "+2 hours" +"%Y-%m-%d %H:%M CEST")
        else
          DATE_TIME=$(date -u -d "+1 hour" +"%Y-%m-%d %H:%M CET")
        fi
        SHORT_SHA="${{ github.sha }}"
        SHORT_SHA=${SHORT_SHA:0:7}
        BRANCH_NAME="${{ github.ref_name }}"
        WORKFLOW_NAME="${{ github.workflow }}"

        # Success percentage and browser setup
        SUCCESS_PERCENT="N/A"; SUCCESS_CLASS="success-medium"
        if [ -f "testResults.json" ]; then
          SUCCESS_PERCENT=$(node -e "try { console.log(Math.round(JSON.parse(require('fs').readFileSync('testResults.json', 'utf8')).PercentPassed || 0) + '%'); } catch(e) { console.log('N/A'); }")
          if [[ "$SUCCESS_PERCENT" != "N/A" ]]; then
            PERCENT_NUM=$(echo "$SUCCESS_PERCENT" | sed 's/%//')
            if [[ $PERCENT_NUM -ge 90 ]]; then
              SUCCESS_CLASS="success-high"
            elif [[ $PERCENT_NUM -ge 30 ]]; then
              SUCCESS_CLASS="success-medium"
            else
              SUCCESS_CLASS="success-low"
            fi
          fi
        fi

        if [[ "${{ inputs.browser-name }}" = "Firefox" ]]; then
          BROWSER_ICON="🦊"
          BROWSER_LABEL="Firefox"
        elif [[ "${{ inputs.browser-name }}" = "Webkit" ]]; then
          BROWSER_ICON="🦎"
          BROWSER_LABEL="WebKit"
        else
          BROWSER_ICON="🌐"
          BROWSER_LABEL="Chrome"
        fi
        if [[ "$WORKFLOW_NAME" == "Manual Penpot Tests for PR" ]]; then
          WORKFLOW_LABEL="PR_manual"
        elif [[ "$WORKFLOW_NAME" =~ firefox ]] || [[ "$WORKFLOW_NAME" =~ Firefox ]]; then
          WORKFLOW_LABEL="PRE_firefox"
        elif [[ "$WORKFLOW_NAME" =~ webkit ]] || [[ "$WORKFLOW_NAME" =~ Webkit ]]; then
          WORKFLOW_LABEL="PRE_webkit"
        else
          WORKFLOW_LABEL="PRE_chrome_daily"
        fi

        # Generate updated index.html
        {
          sed -n '1,/<!-- ROWS_PLACEHOLDER -->/p' .github/html-template.html | head -n -1
          echo "          <tr>"
          echo "            <td class=\"success-rate $SUCCESS_CLASS\" data-label=\"📊 Success %\">$SUCCESS_PERCENT</td>"
          echo "            <td class=\"workflow\" data-label=\"🔄 Workflow\">$WORKFLOW_LABEL</td>"
          echo "            <td class=\"commit\" data-label=\"📝 Commit\"><a href=\"https://github.com/${{ github.repository }}/commit/${{ github.sha }}\">$SHORT_SHA</a></td>"
          echo "            <td class=\"date\" data-label=\"📅 Date\">$DATE_TIME</td>"
          echo "            <td class=\"branch\" data-label=\"🌿 Branch\">$BRANCH_NAME</td>"
          echo "            <td class=\"browser\" data-label=\"🌐 Browser\"><span title=\"$BROWSER_LABEL\">$BROWSER_ICON $BROWSER_LABEL</span></td>"
          echo "            <td data-label=\"📊 Report\"><a href=\"https://kaleidos-qa-reports.s3.eu-west-1.amazonaws.com/run-${{ github.run_id }}/index.html\">🔍 View Report</a></td>"
          echo "          </tr>"
          [ -f current_index.html ] && sed -n '/<tbody>/,/<\/tbody>/p' current_index.html | sed '1d;$d;/<!-- ROWS_PLACEHOLDER -->/d;/^[[:space:]]*$/d' || true
          sed -n '/<!-- ROWS_PLACEHOLDER -->/,$p' .github/html-template.html | tail -n +2
        } > new_index.html

        # Upload updated index to S3 with proper content type and caching
        aws s3 cp new_index.html s3://kaleidos-qa-reports/index.html \
          --content-type "text/html" \
          --cache-control "max-age=300" \
          --metadata-directive REPLACE

        echo "✅ Index updated on S3: https://kaleidos-qa-reports.s3.eu-west-1.amazonaws.com/index.html"

        # Cleanup
        rm -f current_index.html new_index.html

    - name: Upload smart report to S3
      id: upload-smart-report
      shell: bash
      run: |
        echo "🔍 Looking for smart report files..."
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la *.html 2>/dev/null || echo "No HTML files in root"
        echo "Files in playwright-report:"
        ls -la playwright-report/*.html 2>/dev/null || echo "No HTML files in playwright-report"

        # Check for smart report in multiple possible locations
        SMART_REPORT_PATH=""
        if [ -f "smart-report.html" ]; then
          SMART_REPORT_PATH="smart-report.html"
          echo "✅ Found smart-report.html in root"
        elif [ -f "playwright-report/smart-report.html" ]; then
          SMART_REPORT_PATH="playwright-report/smart-report.html"
          echo "✅ Found smart-report.html in playwright-report/"
        elif [ -f "tests/smart-report.html" ]; then
          SMART_REPORT_PATH="tests/smart-report.html"
          echo "✅ Found smart-report.html in tests/"
        else
          echo "❌ smart-report.html not found anywhere"
          echo "Creating a simple placeholder for debugging..."
          echo "<h1>Smart Report Placeholder</h1><p>Generated at $(date)</p>" > smart-report.html
          SMART_REPORT_PATH="smart-report.html"
        fi

        if [ -n "$SMART_REPORT_PATH" ]; then
          echo "📤 Uploading $SMART_REPORT_PATH to S3..."
          aws s3 cp "$SMART_REPORT_PATH" s3://kaleidos-qa-reports/run-${{ github.run_id }}/smart-report.html \
            --content-type "text/html" \
            --cache-control "max-age=300" \
            --metadata-directive REPLACE
          
          SMART_REPORT_URL="https://kaleidos-qa-reports.s3.eu-west-1.amazonaws.com/run-${{ github.run_id }}/smart-report.html"
          echo "smart-report-url=$SMART_REPORT_URL" >> $GITHUB_OUTPUT
          echo "✅ Smart report uploaded: $SMART_REPORT_URL"
        else
          echo "⚠️ No smart report to upload"
          echo "smart-report-url=" >> $GITHUB_OUTPUT
        fi

    - name: Testdino Reporter
      shell: bash
      run: |
        npx --yes tdpw playwright-report/ --token="${{ inputs.testdino_api_key }}" --upload-html  --upload-traces --json-report playwright-report/results.json
        echo "✅ Report uploaded to TestDino ('is-manual-execution': ${{ inputs.is-manual-execution }})"
      if: ${{ inputs.is-manual-execution == 'false'}}

    - name: Upload artifact backup
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: playwright-report/
        retention-days: 7
        if-no-files-found: ignore
      if: ${{ !inputs.is-manual-execution }}
