name: 'Generate and Upload Reports'
description: 'Download existing reports, prepare history and upload to GitHub Pages'

inputs:
  browser-name:
    description: 'Browser name for the report'
    required: true
  artifact-name:
    description: 'Name for the artifact upload'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages
        token: ${{ github.token }}

    - name: Prepare new report
      shell: bash
      run: |
        mkdir -p gh-pages/reports/run-${{ github.run_id }}
        cp -r playwright-report/* gh-pages/reports/run-${{ github.run_id }}/

        DATE_TIME=$(date -u +"%Y-%m-%d %H:%M UTC")
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        BRANCH_NAME="${{ github.ref_name }}"
        WORKFLOW_NAME="${{ github.workflow }}"
        SUCCESS_PERCENT="N/A"
        SUCCESS_CLASS="success-medium"
        if [ -f "testResults.json" ]; then
          SUCCESS_PERCENT=$(node -e "try { const results = JSON.parse(require('fs').readFileSync('testResults.json', 'utf8')); console.log(Math.round(results.PercentPassed || 0) + '%'); } catch(e) { console.log('N/A'); }")
          if [ "$SUCCESS_PERCENT" != "N/A" ]; then
            PERCENT_NUM=$(echo $SUCCESS_PERCENT | sed 's/%//')
            if [ "$PERCENT_NUM" -ge 90 ]; then
              SUCCESS_CLASS="success-high"
            elif [ "$PERCENT_NUM" -ge 30 ]; then
              SUCCESS_CLASS="success-medium"
            else
              SUCCESS_CLASS="success-low"
            fi
          fi
        fi

        BROWSER_ICON="🌐"
        BROWSER_LABEL="Chrome"
        if [ "${{ inputs.browser-name }}" = "Firefox" ]; then
          BROWSER_ICON="🦊"
          BROWSER_LABEL="Firefox"
        fi
        if [[ "$WORKFLOW_NAME" =~ firefox|Firefox ]]; then
          WORKFLOW_LABEL="PRE_daily_firefox"
        else
          WORKFLOW_LABEL="PRE_daily"
        fi

        # Create new row for this execution
        NEW_ROW="          <tr>"
        NEW_ROW+="\n            <td class=\"success-rate $SUCCESS_CLASS\" data-label=\"📊 Success %\">$SUCCESS_PERCENT</td>"
        NEW_ROW+="\n            <td class=\"workflow\" data-label=\"🔄 Workflow\">$WORKFLOW_LABEL</td>"
        NEW_ROW+="\n            <td class=\"commit\" data-label=\"📝 Commit\"><a href=\"https://github.com/${{ github.repository }}/commit/${{ github.sha }}\">$SHORT_SHA</a></td>"
        NEW_ROW+="\n            <td class=\"date\" data-label=\"📅 Date\">$DATE_TIME</td>"
        NEW_ROW+="\n            <td class=\"branch\" data-label=\"🌿 Branch\">$BRANCH_NAME</td>"
        NEW_ROW+="\n            <td class=\"browser\" data-label=\"🌐 Browser\"><span title=\"$BROWSER_LABEL\">$BROWSER_ICON $BROWSER_LABEL</span></td>"
        NEW_ROW+="\n            <td data-label=\"📊 Report\"><a href=\"reports/run-${{ github.run_id }}/index.html\">🔍 View Report</a></td>"
        NEW_ROW+="\n          </tr>"

        # Extract existing rows from current index.html if it exists, excluding header row
        EXISTING_ROWS=""
        if [ -f gh-pages/index.html ]; then
          echo "Extracting existing rows from gh-pages/index.html..."
          # Extract only data rows (not header), limit to 49 most recent
          EXISTING_ROWS=$(sed -n '/<tbody>/,/<\/tbody>/p' gh-pages/index.html | \
                         grep -E '^\s*<tr>' | \
                         grep -v 'data-label.*📊 Success %.*th>' | \
                         head -49 || true)
          echo "Found $(echo "$EXISTING_ROWS" | grep -c '<tr>' || echo 0) existing rows"
        else
          echo "No existing index.html found in gh-pages"
        fi

        # Combine new row with existing rows
        if [ -n "$EXISTING_ROWS" ]; then
          ALL_ROWS="$NEW_ROW"$'\n'"$EXISTING_ROWS"
        else
          ALL_ROWS="$NEW_ROW"
        fi

        # Generate new index.html with all rows
        echo "Generating new index.html with historical data..."
        sed "s|<!-- ROWS_PLACEHOLDER -->|$ALL_ROWS|" .github/html-template.html > gh-pages/index.html

        # Clean up old report directories (keep only 50 most recent)
        if [ -d gh-pages/reports ]; then
          echo "Cleaning up old reports..."
          ls -dt gh-pages/reports/run-* 2>/dev/null | tail -n +51 | xargs -r rm -rf
          echo "Kept $(ls -1 gh-pages/reports/ 2>/dev/null | wc -l) report directories"
        fi

    - name: Commit and push to gh-pages
      shell: bash
      run: |
        cd gh-pages
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Add report for run ${{ github.run_id }}" || echo "No changes to commit"
        git push origin gh-pages
