name: 'Generate and Upload Reports'
description: 'Download existing reports, prepare history and upload to GitHub Pages'

inputs:
  browser-name:
    description: 'Browser name for the report'
    required: true
  artifact-name:
    description: 'Name for the artifact upload'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages
        token: ${{ github.token }}

    - name: Prepare new report
      shell: bash
      run: |
        mkdir -p gh-pages/reports/run-${{ github.run_id }}
        cp -r playwright-report/* gh-pages/reports/run-${{ github.run_id }}/

        DATE_TIME=$(date -u +"%Y-%m-%d %H:%M UTC")
        SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
        BRANCH_NAME="${{ github.ref_name }}"
        WORKFLOW_NAME="${{ github.workflow }}"
        SUCCESS_PERCENT="N/A"
        SUCCESS_CLASS="success-medium"
        if [ -f "testResults.json" ]; then
          SUCCESS_PERCENT=$(node -e "try { const results = JSON.parse(require('fs').readFileSync('testResults.json', 'utf8')); console.log(Math.round(results.PercentPassed || 0) + '%'); } catch(e) { console.log('N/A'); }")
          if [ "$SUCCESS_PERCENT" != "N/A" ]; then
            PERCENT_NUM=$(echo $SUCCESS_PERCENT | sed 's/%//')
            if [ "$PERCENT_NUM" -ge 90 ]; then
              SUCCESS_CLASS="success-high"
            elif [ "$PERCENT_NUM" -ge 30 ]; then
              SUCCESS_CLASS="success-medium"
            else
              SUCCESS_CLASS="success-low"
            fi
          fi
        fi

        cp .github/html-template.html gh-pages/index.html

        BROWSER_ICON="🌐"
        BROWSER_LABEL="Chrome"
        if [ "${{ inputs.browser-name }}" = "Firefox" ]; then
          BROWSER_ICON="🦊"
          BROWSER_LABEL="Firefox"
        fi
        if [[ "$WORKFLOW_NAME" =~ firefox|Firefox ]]; then
          WORKFLOW_LABEL="PRE_daily_firefox"
        else
          WORKFLOW_LABEL="PRE_daily"
        fi

        NEW_ROW="<tr>"
        NEW_ROW+="<td class=\"success-rate $SUCCESS_CLASS\" data-label=\"📊 Success %\">$SUCCESS_PERCENT</td>"
        NEW_ROW+="<td class=\"workflow\" data-label=\"🔄 Workflow\">$WORKFLOW_LABEL</td>"
        NEW_ROW+="<td class=\"commit\" data-label=\"📝 Commit\"><a href=\"https://github.com/${{ github.repository }}/commit/${{ github.sha }}\">$SHORT_SHA</a></td>"
        NEW_ROW+="<td class=\"date\" data-label=\"📅 Date\">$DATE_TIME</td>"
        NEW_ROW+="<td class=\"branch\" data-label=\"🌿 Branch\">$BRANCH_NAME</td>"
        NEW_ROW+="<td class=\"browser\" data-label=\"🌐 Browser\"><span title=\"$BROWSER_LABEL\">$BROWSER_ICON $BROWSER_LABEL</span></td>"
        NEW_ROW+="<td data-label=\"📊 Report\"><a href=\"reports/run-${{ github.run_id }}/index.html\">🔍 View Report</a></td>"
        NEW_ROW+="</tr>"

        ROWS_CONTENT="$NEW_ROW"
        if [ -f gh-pages/index.html ]; then
          EXISTING_ROWS=$(grep "<tr>" gh-pages/index.html | head -49 | tr '\n' ' ' || true)
          ROWS_CONTENT="$NEW_ROW $EXISTING_ROWS"
        fi
        sed "s|<!-- ROWS_PLACEHOLDER -->|$ROWS_CONTENT|" .github/html-template.html > gh-pages/index.html

        if [ -d gh-pages/reports ]; then
          ls -dt gh-pages/reports/run-* 2>/dev/null | tail -n +51 | xargs -r rm -rf
        fi

    - name: Commit and push to gh-pages
      shell: bash
      run: |
        cd gh-pages
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Add report for run ${{ github.run_id }}" || echo "No changes to commit"
        git push origin gh-pages
