name: 'Send Mattermost Notification'
description: 'Send test results notification to Mattermost'

inputs:
  mattermost-webhook-url:
    description: 'Mattermost webhook URL'
    required: true
  browser-name:
    description: 'Browser name for the notification'
    required: true
  folder-path:
    description: 'Test folder path (optional)'
    required: false
  is-manual-execution:
    description: 'Whether this is a manual execution (true/false)'
    required: false
    default: 'false'
  username:
    description: 'Username for manual execution mention'
    required: false
  smart-report-url:
    description: 'URL of the smart report'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Generate Mattermost message content
      id: message
      shell: bash
      run: |
        FOLDER_PATH="${{ inputs.folder-path }}"
        IS_MANUAL="${{ inputs.is-manual-execution }}"
        USERNAME="${{ inputs.username }}"
        SMART_REPORT_URL="${{ inputs.smart-report-url }}"

        echo "🔍 Debug info:"
        echo "Smart Report URL input: '$SMART_REPORT_URL'"
        echo "Browser: ${{ inputs.browser-name }}"

        # Generate the message content and save to output
        if [ -n "$FOLDER_PATH" ]; then
          if [ "$IS_MANUAL" = "true" ] && [ -n "$USERNAME" ]; then
            MESSAGE=$(npx ts-node -e "require('./helpers/mattermost.helper.js').generateMessage('${{ inputs.browser-name }}', '$FOLDER_PATH', true, '$USERNAME', '$SMART_REPORT_URL')")
          else
            MESSAGE=$(npx ts-node -e "require('./helpers/mattermost.helper.js').generateMessage('${{ inputs.browser-name }}', '$FOLDER_PATH', false, null, '$SMART_REPORT_URL')")
          fi
        else
          if [ "$IS_MANUAL" = "true" ] && [ -n "$USERNAME" ]; then
            MESSAGE=$(npx ts-node -e "require('./helpers/mattermost.helper.js').generateMessage('${{ inputs.browser-name }}', null, true, '$USERNAME', '$SMART_REPORT_URL')")
          else
            MESSAGE=$(npx ts-node -e "require('./helpers/mattermost.helper.js').generateMessage('${{ inputs.browser-name }}', null, false, null, '$SMART_REPORT_URL')")
          fi
        fi

        # Save message to output, handling multiline content
        echo "message<<EOF" >> $GITHUB_OUTPUT
        echo "$MESSAGE" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Send Mattermost notification
      if: always()
      uses: mattermost/action-mattermost-notify@master
      with:
        MATTERMOST_WEBHOOK_URL: ${{ inputs.mattermost-webhook-url }}
        TEXT: ${{ steps.message.outputs.message }}
