name: 'Setup Test History and Baseline'
description: 'Downloads test history from S3 and configures baseline for comparisons'

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true

outputs:
  baseline-run-id:
    description: 'Baseline run ID for comparison'
    value: ${{ steps.setup-baseline.outputs.baseline-run-id }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Download test history from S3
      shell: bash
      run: |
        mkdir -p history

        # Clean branch name for folder structure
        CLEAN_BRANCH=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/_/g')
        mkdir -p "history/${CLEAN_BRANCH}"

        # Download main history file
        aws s3 cp s3://kaleidos-qa-reports/test-history.json test-history.json 2>/dev/null || echo "No main history file found"

        # Debug downloaded file
        if [ -f "test-history.json" ]; then
          echo "📥 Downloaded main history file: $(wc -c < test-history.json) bytes"
          echo "🔍 Downloaded file structure: $(node -pe 'try { const h=JSON.parse(require("fs").readFileSync("test-history.json", "utf8")); Object.keys(h).join(",") } catch(e) { "error" }')"
          echo "🔍 Downloaded file runs: $(node -pe 'try { JSON.parse(require("fs").readFileSync("test-history.json", "utf8")).runs?.length || 0 } catch(e) { 0 }')"
        fi

        # Download branch-specific history files
        aws s3 sync s3://kaleidos-qa-reports/history/${CLEAN_BRANCH}/ history/${CLEAN_BRANCH}/ 2>/dev/null || echo "No branch-specific history found"

        # Debug branch files
        if [ -d "history/${CLEAN_BRANCH}" ]; then
          echo "📁 Branch history files found:"
          ls -la "history/${CLEAN_BRANCH}/" || echo "No files in branch directory"
          
          for file in history/${CLEAN_BRANCH}/history_*.json; do
            if [ -f "$file" ]; then
              echo "📄 Branch file: $file ($(wc -c < "$file") bytes)"
              echo "🔍 Branch file runs: $(node -pe 'try { JSON.parse(require("fs").readFileSync("'$file'", "utf8")).runs?.length || 0 } catch(e) { 0 }')"
            fi
          done
        fi

    - name: Merge test histories
      shell: bash
      run: |
        CLEAN_BRANCH=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/_/g')

        # Create array of history files to merge
        HISTORY_FILES=()

        # Add main history file if it exists AND has runs > 0
        if [ -f "test-history.json" ]; then
          RUNS_COUNT=$(node -pe 'try { JSON.parse(require("fs").readFileSync("test-history.json", "utf8")).runs?.length || 0 } catch(e) { 0 }')
          if [ "$RUNS_COUNT" -gt 0 ]; then
            HISTORY_FILES+=("test-history.json")
            echo "Found main history file with $RUNS_COUNT runs: test-history.json"
          else
            echo "⚠️ Skipping main history file (0 runs): test-history.json"
          fi
        fi

        # Add branch-specific history files if they have runs > 0
        if [ -d "history/${CLEAN_BRANCH}" ]; then
          for file in history/${CLEAN_BRANCH}/history_*.json; do
            if [ -f "$file" ]; then
              RUNS_COUNT=$(node -pe 'try { JSON.parse(require("fs").readFileSync("'$file'", "utf8")).runs?.length || 0 } catch(e) { 0 }')
              if [ "$RUNS_COUNT" -gt 0 ]; then
                HISTORY_FILES+=("$file")
                echo "Found branch history file with $RUNS_COUNT runs: $file"
              else
                echo "⚠️ Skipping branch history file (0 runs): $file"
              fi
            fi
          done
        fi

        # If we have multiple valid history files, merge them
        if [ ${#HISTORY_FILES[@]} -gt 1 ]; then
          echo "Merging ${#HISTORY_FILES[@]} valid history files..."
          
          # Debug: show content of each file before merge
          for file in "${HISTORY_FILES[@]}"; do
            if [ -f "$file" ]; then
              echo "📄 File: $file ($(wc -c < "$file") bytes)"
              echo "🔍 Runs in $file: $(node -pe 'try { JSON.parse(require("fs").readFileSync("'$file'", "utf8")).runs?.length || 0 } catch(e) { 0 }')"
              echo "🔍 Tests in $file: $(node -pe 'try { Object.keys(JSON.parse(require("fs").readFileSync("'$file'", "utf8")).tests || {}).length } catch(e) { 0 }')"
            fi
          done
          
          npx playwright-smart-reporter-merge-history "${HISTORY_FILES[@]}" -o merged-history.json --max-runs 15
          
          if [ -f "merged-history.json" ]; then
            mv merged-history.json test-history.json
            echo "✅ Successfully merged history files"
            echo "📊 Merged history runs count: $(node -pe 'try { JSON.parse(require("fs").readFileSync("test-history.json", "utf8")).runs?.length || 0 } catch(e) { 0 }')"
          else
            echo "❌ Failed to merge history files"
          fi
        elif [ ${#HISTORY_FILES[@]} -eq 1 ]; then
          echo "Using single valid history file: ${HISTORY_FILES[0]}"
          echo "🔍 Single file runs count: $(node -pe 'try { JSON.parse(require("fs").readFileSync("'${HISTORY_FILES[0]}'", "utf8")).runs?.length || 0 } catch(e) { 0 }')"
          # Copy to root location if not already there
          if [ "${HISTORY_FILES[0]}" != "test-history.json" ]; then
            cp "${HISTORY_FILES[0]}" test-history.json
          fi
        else
          echo "🔄 No valid history files with runs found. Creating empty baseline for new run."
          # Create empty baseline history that will be populated by the current run
          echo "   Tests: $(node -pe 'try { Object.keys(JSON.parse(require("fs").readFileSync("test-history.json", "utf8")).tests || {}).length } catch(e) { 0 }')"
        fi

    - name: Setup baseline run ID
      id: setup-baseline
      shell: bash
      run: |
        # Generate unique baseline run ID based on timestamp and commit
        BASELINE_ID="${{ github.sha }}_$(date +%s)"
        echo "baseline-run-id=${BASELINE_ID}" >> $GITHUB_OUTPUT
        echo "📝 Baseline Run ID set to: ${BASELINE_ID}"

        # Export for use in subsequent steps
        echo "BASELINE_RUN_ID=${BASELINE_ID}" >> $GITHUB_ENV
