name: 'Setup Test History and Baseline'
description: 'Downloads test history from S3 and configures baseline for comparisons'

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true

outputs:
  baseline-run-id:
    description: 'Baseline run ID for comparison'
    value: ${{ steps.setup-baseline.outputs.baseline-run-id }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Download test history from S3
      shell: bash
      run: |
        mkdir -p history

        # Clean branch name for folder structure
        CLEAN_BRANCH=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/_/g')
        mkdir -p "history/${CLEAN_BRANCH}"

        # Download main history file
        aws s3 cp s3://kaleidos-qa-reports/test-history.json test-history.json 2>/dev/null

        # Download branch-specific history files
        aws s3 sync s3://kaleidos-qa-reports/history/${CLEAN_BRANCH}/ history/${CLEAN_BRANCH}/ 2>/dev/null

    - name: Setup baseline for comparison
      id: setup-baseline
      shell: bash
      run: |
        CLEAN_BRANCH=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/_/g')

        # Configure baseline for comparison
        if [ -d "history/${CLEAN_BRANCH}" ] && [ "$(ls -A history/${CLEAN_BRANCH})" ]; then
          LATEST_HISTORY=$(ls -t history/${CLEAN_BRANCH}/history_*.json 2>/dev/null | head -1)
          if [ -n "$LATEST_HISTORY" ]; then
            BASELINE_ID=$(basename "$LATEST_HISTORY" | sed 's/history_\([0-9]*\)_.*/\1/')
            echo "BASELINE_RUN_ID=$BASELINE_ID" >> $GITHUB_ENV
            echo "baseline-run-id=$BASELINE_ID" >> $GITHUB_OUTPUT
          else
            echo "baseline-run-id=" >> $GITHUB_OUTPUT
          fi
        else
          echo "baseline-run-id=" >> $GITHUB_OUTPUT
        fi
