name: 'Setup Test History and Baseline'
description: 'Downloads test history from S3 for smart reporter'

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Download test history from S3
      shell: bash
      run: |
        # Use branch-specific history files
        CLEAN_BRANCH=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9._-]/_/g')
        echo "🔍 Looking for test-history files for branch: ${CLEAN_BRANCH}"

        # Download test-history files specific to this branch
        mkdir -p "history/${CLEAN_BRANCH}"
        aws s3 sync s3://kaleidos-qa-reports/history/${CLEAN_BRANCH}/ history/${CLEAN_BRANCH}/ --exclude "*" --include "test-history*" 2>/dev/null || echo "No test-history files found for branch ${CLEAN_BRANCH}"

        # Find the largest test-history file for this branch (most complete)
        BEST_FILE=""
        BEST_SIZE=0

        for file in history/${CLEAN_BRANCH}/test-history*.json; do
          if [ -f "$file" ]; then
            FILE_SIZE=$(wc -c < "$file")
            echo "📄 Found: $file (${FILE_SIZE} bytes)"
            
            if [ "$FILE_SIZE" -gt "$BEST_SIZE" ]; then
              BEST_FILE="$file"
              BEST_SIZE="$FILE_SIZE"
            fi
          fi
        done

        if [ -n "$BEST_FILE" ]; then
          echo "✅ Using: $BEST_FILE"
          cp "$BEST_FILE" test-history.json
          echo "📊 Branch-specific history loaded for: ${CLEAN_BRANCH}"
          
          # Extract the most recent run ID from history for baseline
          BASELINE_RUN_ID=$(node -pe 'try { 
            const history = JSON.parse(require("fs").readFileSync("test-history.json", "utf8")); 
            const runs = history.runs || []; 
            runs.length > 0 ? runs[runs.length - 1].id || runs[0].id : "" 
          } catch(e) { "" }')
          
          if [ -n "$BASELINE_RUN_ID" ]; then
            echo "BASELINE_RUN_ID=${BASELINE_RUN_ID}" >> $GITHUB_ENV
            echo "🎯 Baseline Run ID set to: ${BASELINE_RUN_ID}"
          else
            echo "⚠️ Could not extract baseline run ID from history"
          fi
        else
          echo "ℹ️ No test-history files found for branch ${CLEAN_BRANCH}, smart reporter will start fresh"
        fi
