name: Fix GitHub Pages History

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'check'
        type: choice
        options:
          - check
          - reset
          - repair

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  fix-history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fix GitHub Pages History
        uses: ./.github/actions/fix-history
        with:
          action: ${{ github.event.inputs.action }}
