name: Fix GitHub Pages History

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'check'
        type: choice
        options:
          - check
          - reset
          - repair

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  fix-history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          token: ${{ github.token }}

      - name: Check history status
        if: github.event.inputs.action == 'check'
        run: |
          echo "=== GitHub Pages History Status ==="

          if [ -f gh-pages/index.html ]; then
            echo "✅ index.html exists"
            ROW_COUNT=$(grep -c '<tr>' gh-pages/index.html || echo 0)
            DATA_ROWS=$(sed -n '/<tbody>/,/<\/tbody>/p' gh-pages/index.html | grep -c '<tr>' || echo 0)
            echo "📊 Total rows: $ROW_COUNT"
            echo "📊 Data rows: $DATA_ROWS"
            
            if [ -d gh-pages/reports ]; then
              REPORT_COUNT=$(ls -1 gh-pages/reports/ | wc -l)
              echo "📁 Report directories: $REPORT_COUNT"
            else
              echo "❌ No reports directory found"
            fi
          else
            echo "❌ No index.html found"
          fi

      - name: Reset history
        if: github.event.inputs.action == 'reset'
        run: |
          echo "🔄 Resetting GitHub Pages history..."

          # Keep reports but reset index.html
          cp .github/html-template.html gh-pages/index.html

          # Add a placeholder message
          PLACEHOLDER_ROW="          <tr>"
          PLACEHOLDER_ROW+="\n            <td class=\"success-rate success-medium\" data-label=\"📊 Success %\" colspan=\"7\">"
          PLACEHOLDER_ROW+="\n              <em>No test results yet. Run a test workflow to populate this table.</em>"
          PLACEHOLDER_ROW+="\n            </td>"
          PLACEHOLDER_ROW+="\n          </tr>"

          sed "s|<!-- ROWS_PLACEHOLDER -->|$PLACEHOLDER_ROW|" .github/html-template.html > gh-pages/index.html

          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Reset GitHub Pages history" || echo "No changes to commit"
          git push origin gh-pages

      - name: Repair history
        if: github.event.inputs.action == 'repair'
        run: |
          echo "🔧 Attempting to repair history from existing reports..."

          if [ ! -d gh-pages/reports ]; then
            echo "❌ No reports directory found. Cannot repair history."
            exit 1
          fi

          # Start with clean template
          cp .github/html-template.html gh-pages/index.html

          # Generate rows from existing reports (newest first)
          ALL_ROWS=""
          for report_dir in $(ls -dt gh-pages/reports/run-* 2>/dev/null | head -50); do
            RUN_ID=$(basename "$report_dir" | sed 's/run-//')
            
            # Try to extract info from report or use defaults
            DATE_TIME=$(stat -c %y "$report_dir" 2>/dev/null | cut -d' ' -f1,2 | sed 's/ / /' || echo "Unknown")
            
            ROW="          <tr>"
            ROW+="\n            <td class=\"success-rate success-medium\" data-label=\"📊 Success %\">N/A</td>"
            ROW+="\n            <td class=\"workflow\" data-label=\"🔄 Workflow\">Recovered</td>"
            ROW+="\n            <td class=\"commit\" data-label=\"📝 Commit\">N/A</td>"
            ROW+="\n            <td class=\"date\" data-label=\"📅 Date\">$DATE_TIME</td>"
            ROW+="\n            <td class=\"branch\" data-label=\"🌿 Branch\">N/A</td>"
            ROW+="\n            <td class=\"browser\" data-label=\"🌐 Browser\">🌐 Chrome</td>"
            ROW+="\n            <td data-label=\"📊 Report\"><a href=\"reports/run-$RUN_ID/index.html\">🔍 View Report</a></td>"
            ROW+="\n          </tr>"
            
            if [ -z "$ALL_ROWS" ]; then
              ALL_ROWS="$ROW"
            else
              ALL_ROWS="$ALL_ROWS"$'\n'"$ROW"
            fi
          done

          if [ -n "$ALL_ROWS" ]; then
            sed "s|<!-- ROWS_PLACEHOLDER -->|$ALL_ROWS|" .github/html-template.html > gh-pages/index.html
            echo "✅ Repaired history with $(echo "$ALL_ROWS" | grep -c '<tr>') entries"
          else
            echo "❌ No reports found to repair from"
            exit 1
          fi

          cd gh-pages
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add index.html
          git commit -m "Repair GitHub Pages history from existing reports" || echo "No changes to commit"
          git push origin gh-pages
