name: Penpot Regression Tests on PRE env (weekly)
on:
  schedule: ## run tests each Thursday at 8:00pm UTC
    - cron: '00 20 * * 4'
  workflow_dispatch:

jobs:
  tests_chromium:
    environment: PRE
    timeout-minutes: 180
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          LOGIN_EMAIL: ${{ secrets.SECOND_EMAIL }}
          LOGIN_PWD: ${{ secrets.LOGIN_PWD }}
          GITHUB_RUN_ID: ${{ github.run.id }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          GMAIL_NAME: ${{ secrets.GMAIL_NAME }}
        run: npx playwright test --project=webkit -gv 'PERF' ./tests/panels-features/panels-features-fill.spec.js
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-kit
          path: playwright-report/
          retention-days: 30
      - name: Send mattermost Message
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          LOGIN_ID_MATTERMOST: ${{ secrets.LOGIN_ID_MATTERMOST }}
          PASSWORD_MATTERMOST: ${{ secrets.PASSWORD_MATTERMOST }}
        if: always()
        run: npx ts-node -e "require('./helpers/mattermost.helper.js').sendMessage('Kit')"
